// Generated by Finicky Kickstart (not anymore :P)
// https://finicky-kickstart.vercel.app/
// Save as ~/.finicky.js

const personalBrowser = {
    name: "Google Chrome",
    profile: "Default"
};
const gitHubApp = ({urlString}) => ({
    name: "Google Chrome",
    profile: "Default",
    args: [
        `--app-id=mjoklplbddabcmpepnokjaffbmgbkkgg`,
        `--app-launch-url-for-shortcuts-menu-item=${urlString}`,
    ],
})

module.exports = {
    defaultBrowser: "Google Chrome",
    handlers: [
        {
            match: ({url}) => url.host.endsWith("github.com"),
            browser: gitHubApp,
        },
        {
            match: ({url}) => url.host.endsWith("notion.so"),
            browser: {
                name: "Notion",
            },
        },
        {
            match: ({url}) => url.host.endsWith("linkedin.com"),
            browser: personalBrowser,
        }
    ]
}
